homeassistant:
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - sensor:
      - name: "PM2.5 Grid A1"
        unique_id: pm25_grid_a1
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((0 - 2)**2 + (0 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((0 - 0)**2 + (0 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((0 - 3)**2 + (0 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid A2"
        unique_id: pm25_grid_a2
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((1 - 2)**2 + (0 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((1 - 0)**2 + (0 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((1 - 3)**2 + (0 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid A3"
        unique_id: pm25_grid_a3
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((2 - 2)**2 + (0 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((2 - 0)**2 + (0 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((2 - 3)**2 + (0 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid A4"
        unique_id: pm25_grid_a4
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((3 - 2)**2 + (0 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((3 - 0)**2 + (0 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((3 - 3)**2 + (0 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid B1"
        unique_id: pm25_grid_b1
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((0 - 2)**2 + (1 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((0 - 0)**2 + (1 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((0 - 3)**2 + (1 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid B2"
        unique_id: pm25_grid_b2
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((1 - 2)**2 + (1 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((1 - 0)**2 + (1 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((1 - 3)**2 + (1 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid B3"
        unique_id: pm25_grid_b3
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((2 - 2)**2 + (1 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((2 - 0)**2 + (1 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((2 - 3)**2 + (1 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}
          
      - name: "PM2.5 Grid B4"
        unique_id: pm25_grid_b4
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((3 - 2)**2 + (1 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((3 - 0)**2 + (1 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((3 - 3)**2 + (1 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

          
      - name: "PM2.5 Grid C1"
        unique_id: pm25_grid_c1
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((0 - 2)**2 + (2 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((0 - 0)**2 + (2 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((0 - 3)**2 + (2 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid C2"
        unique_id: pm25_grid_c2
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((1 - 2)**2 + (2 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((1 - 0)**2 + (2 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((1 - 3)**2 + (2 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid C3"
        unique_id: pm25_grid_c3
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((2 - 2)**2 + (2 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((2 - 0)**2 + (2 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((2 - 3)**2 + (2 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}
          
      - name: "PM2.5 Grid C4"
        unique_id: pm25_grid_c4
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((3 - 2)**2 + (2 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((3 - 0)**2 + (2 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((3 - 3)**2 + (2 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}
          
          
      - name: "PM2.5 Grid D1"
        unique_id: pm25_grid_d1
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((0 - 2)**2 + (3 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((0 - 0)**2 + (3 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((0 - 3)**2 + (3 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid D2"
        unique_id: pm25_grid_d2
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((1 - 2)**2 + (3 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((1 - 0)**2 + (3 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((1 - 3)**2 + (3 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}

      - name: "PM2.5 Grid D3"
        unique_id: pm25_grid_d3
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((2 - 2)**2 + (3 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((2 - 0)**2 + (3 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((2 - 3)**2 + (3 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}
          
      - name: "PM2.5 Grid D4"
        unique_id: pm25_grid_d4
        unit_of_measurement: "µg/m³"
        state: >
          {% set p1 = states('sensor.zone_aq_1_pm2_5') | float %}
          {% set p2 = states('sensor.zone_aq_2_pm2_5') | float %}
          {% set p3 = states('sensor.zone_aq_3_pm2_5') | float %}
          {% set d1 = ((3 - 2)**2 + (3 - 0)**2)**0.5 + 0.01 %}
          {% set d2 = ((3 - 0)**2 + (3 - 2)**2)**0.5 + 0.01 %}
          {% set d3 = ((3 - 3)**2 + (3 - 3)**2)**0.5 + 0.01 %}
          {% set w1 = 1 / d1 %}
          {% set w2 = 1 / d2 %}
          {% set w3 = 1 / d3 %}
          {% set total = w1 + w2 + w3 %}
          {{ ((p1 * w1) + (p2 * w2) + (p3 * w3)) / total }}
        
          
