substitutions:
  name: "Studio AQ 2"

esphome:
  name: air-quality-studio-2
  on_boot:
    priority: -10
    then:
      - delay: 5s

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:

uart:
  rx_pin: GPIO12
  baud_rate: 9600

sensor:
  - platform: pm1006
    id: aq_sensor
    pm_2_5:
      name: $name PM2.5


